#spring.application.name=configServer

server:
  port: 8888

spring:
  application:
    name: msvc-configServer
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations